name: Build Floating Viewer
on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JS dependencies
        run: npm install --no-audit --no-fund

      - uses: dtolnay/rust-toolchain@stable

      - name: Build PopFS (Tauri)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: 'false'
        with:
          tauriScript: npx tauri
          projectPath: src-tauri

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: popfs-${{ runner.os }}-${{ github.run_number }}
          path: src-tauri/target/release/bundle/**


